---

- name: Create directory .kube
  ansible.legacy.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  ansible.legacy.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="
  changed_when: false

- name: Edit default cluster apiserver endpoint
  when: k3s_apiserver_endpoint is defined and k3s_apiserver_endpoint != ansible_host
  ansible.legacy.command:
    cmd: "k3s kubectl config \
            set-cluster default \
            --server=https://{{ k3s_apiserver_endpoint }}:6443 \
            --kubeconfig ~{{ ansible_user }}/.kube/config"
  changed_when: false
