---

- name: Prepare
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- name: Install masters
  hosts: master
  become: true
  roles:
    - role: k3s_master

# Separate play!
- name: Configure masters
  hosts: master
  become: true
  roles:
    - role: config_kubeconfig
    - role: config_token

- name: Install nodes
  hosts: node
  become: true
  roles:
    - role: k3s_node
