---

name: Lint PR

'on':
  pull_request:
    branches:
      - main

jobs:

  test:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        ansible: ["2.12", "latest"]

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: .requirements/${{ matrix.ansible }}.txt

      - name: Install/upgrade pip, wheel
        run: pip install --upgrade pip wheel

      - name: Install test dependencies
        run: pip install -r .requirements/${{ matrix.ansible }}.txt

      - name: Run yamllint
        run: yamllint .

      # - name: Install ansible requirements
      #   run: ansible-galaxy install -r requirements.yml

      - name: Run ansible-lint
        run: ansible-lint -vv

      # - name: Run ansible-lint
      #   run: ansible-lint -c .ansible-lint -v

      # - name: Upload ansible-lint SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     # Path to SARIF file relative to the root of the repository
      #     sarif_file: ansible-lint-results.sarif
      #     # Optional category for the results
      #     # Used to differentiate multiple results for one commit
      #     category: ansible-lint
